### ISSUE TITLE
Closed auction card needs work

### ISSUE THREAD

**Issue by the-dusky** [stakeordie/scrt-auction#10]
<img width="428" alt="Screen Shot 2021-01-21 at 11 22 12 PM" src="https://user-images.githubusercontent.com/1363641/105446208-79fbf480-5c26-11eb-9e5b-67ce14f12a76.png">

**Comment by cankisagun** [comment]
@the-dusky I would replace "Ends at..." with 2 options
1) For completed auctions (there was a winning bid), we show the price
2) For cancelled auctions, we write cancelled by the seller
