### ISSUE TITLE
List of Closed Auctions showing "Invalid Date"

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#11]
When viewing the list of "closed" auctions, the end date is displaying as "Invalid Date".

![image](https://user-images.githubusercontent.com/436905/105745582-6ee9e280-5f0c-11eb-8227-6704c44b87de.png)

It should show the date/time the auction ended.

**Comment by cankisagun** [comment]
see issue #10

**Comment by lauraweindorf** [comment]
Closed auctions are no longer displayed and all other dates are looking good!
