### ISSUE TITLE
UI Improvement for "sell" and "min bid" at top

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#12]
It wasn't clear to me that these were filters, initially, until I clicked the dropdowns and started choosing specific coins.

![image](https://user-images.githubusercontent.com/436905/105746034-f0da0b80-5f0c-11eb-9b1b-4fa48a39539a.png)

I think it would be great to make it more clear that those are search filters.

Also, the "min bid" label doesn't seem to fit because the user's not really filtering on minimum bid amounts.

**Comment by cankisagun** [comment]
@the-dusky building on Laura's comment,

We should change the boxes and text as:
I want to buy [search buy token] for [search sell token]. _This makes more sense b/c the landing screen is for buyers not sellers. Also I'm open to a different word then buy X **for** y_
