### ISSUE TITLE
Auction Info is difficult to read

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#14]
It would be great if this was styled so it's easier on the eyes. 😄 

![image](https://user-images.githubusercontent.com/436905/105748292-ee2ce580-5f0f-11eb-879c-f3a86f47e6a7.png)

Suggestions:
- differentiate between the label and data or content
- a bit more vertical spacing for the font that's being used
- vary the font choices a bit (?)
- for the "Status" label it says "Accepting Bids: " and then a note or info, maybe that could be on the next line and italicized or something

**Comment by cankisagun** [comment]
I think we can replicate the grid view format (look and feel) here. Some helpful language would be:
First line or something like that: "Selling [amount] [sell token] for [bid token]"
Second line: Price [selling token] / [buying token]

End time:

Status: -> as I mentioned let's remove token sold have been consigned b/c it's default mode.. Status would be accepting bids

Description:

Bid: You have no open bid on this auction -> this part we can merge with status part (could be accepting bids, you have no open bids
