### ISSUE TITLE
Clicking on Logo takes user to "lorem ipsum" page

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#15]
I clicked on the Secret Network logo and it took me to this page.

![image](https://user-images.githubusercontent.com/436905/105748961-cab66a80-5f10-11eb-9e8a-b4c4464b1da3.png)

**Comment by baedrik** [comment]
Also, the FAQs link takes you to a description of Flare.  I know the FAQ will be one of the last things to add.  I just wanted to leave this as a note so it isn't forgotten

**Comment by cankisagun** [comment]
Let's kill these pages for now and we will add them as we get those pages ready
