### ISSUE TITLE
Add a "back" button to the Auction Info page

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#17]
Clicking on the "Bid" button takes you to the Auction Info page where you can bid, or close an auction if it's ended.

It would be nice to give the user a visual element to click to go back to the dashboard or grid/list of auctions.

![image](https://user-images.githubusercontent.com/436905/105751195-b0ca5700-5f13-11eb-95cf-454c3e4778aa.png)

**Comment by lauraweindorf** [comment]
It might not be obvious to all users that they can click on "Auctions" link at the top.

**Comment by cankisagun** [comment]
we can add a backwards arrow like in browsers
![Uploading image.png…]()

**Comment by lauraweindorf** [comment]
This seems to have been addressed by the addition of this left-side panel!
![image](https://user-images.githubusercontent.com/436905/110504115-d6c64800-80ca-11eb-8702-90e595063545.png)
