### ISSUE TITLE
Entering bid price modifies the minimum bid value

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#18]
Two snapshots below: 1) showing the initial state of the bid price and minimum bid info and 2) the values of the fields after the default bid price has been modified.

Not sure why the minimum bid price changes as you modify the bid price. If it's correct behavior, maybe add a note to that area explaining what's happening.

![image](https://user-images.githubusercontent.com/436905/105751585-377f3400-5f14-11eb-8c7e-3070027d7f3b.png)

![image](https://user-images.githubusercontent.com/436905/105751616-449c2300-5f14-11eb-9be9-297f082239b6.png)

I changed the bid price to 340 and the minimum bid field was automatically updated to be 1700.

**Comment by cankisagun** [comment]
Yep, as I pointed before that should be bid - not minimum bid and if the bid is lower than minimum bid, we should give an error like we do in the bridge UI
![image](https://user-images.githubusercontent.com/15679491/105753959-75318c00-5f17-11eb-85fd-c050a5e7f04d.png)

**Comment by cankisagun** [comment]
I am marking this critical. @the-dusky based on what we discussed we are changing min bid with min price here :)
