### ISSUE TITLE
In grid or list view of auctions make status of auctions more noticeable

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#19]
When you filter on the auctions and include both "Open" and "Closed", it's not obvious right away which ones are open and which are closed. Maybe there are UI changes that could help with that? The only thing that gives it away for me is the missing "Bid" button.

![image](https://user-images.githubusercontent.com/436905/105752112-e0c62a00-5f14-11eb-8b6a-cf34931a818b.png)

**Comment by cankisagun** [comment]
Building on this, I think `bid` button should not fade away and should always be visible for live auctions
![image](https://user-images.githubusercontent.com/15679491/105754179-c04b9f00-5f17-11eb-8dbc-e6e60d6d3260.png)

when my mouse is elsewhere
![image](https://user-images.githubusercontent.com/15679491/105754207-c9d50700-5f17-11eb-82ed-60b9895dfe5c.png)

Also, when filtering, clicking on active should show user the active auctions. Currently when you click on active you select or de-select active auctions. There's not a use case where the user needs to see active and closed auctions in the same page

**Comment by cankisagun** [comment]
Since we are removing closed auctions from the UI for now, marking this as medium priority
