### ISSUE TITLE
Auction mainpage UI - decimal points

### ISSUE THREAD

**Issue by cankisagun** [stakeordie/scrt-auction#2]
Let’s fix decimal points (can wait after launch) 

_1st line_ 
    - Number and unit being sold should be on the same line We have first line read “Selling 90.00 TSUNI”
_2nd line_ 
    - Same number of decimal points -> 810.00 TSDAI
![image](https://user-images.githubusercontent.com/15679491/105410032-5a050a80-5bff-11eb-9f04-155d3f69e88a.png)

**Comment by the-dusky** [comment]
<img width="1244" alt="Screen Shot 2021-01-21 at 11 20 44 PM" src="https://user-images.githubusercontent.com/1363641/105446043-2a1d2d80-5c26-11eb-8add-1b62fcca799b.png">

**Comment by the-dusky** [comment]
Updated. I think this is fixed, but will leave open until I am sure.
