### ISSUE TITLE
Not clear what user needs to do for the Viewing Keys

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#20]
When I first clicked on the Key icon, I saw the viewing key for the "Factory address" and a button to create a viewing key.

I went ahead and created a viewing key, but I'm not sure that I needed to ... also, what is the UI referring to for the factory address?

![image](https://user-images.githubusercontent.com/436905/105755394-3e5c7580-5f19-11eb-95c5-9735be954d3c.png)

I think maybe just adding a bit of verbiage to that window would make it easier for the user to understand.

**Comment by cankisagun** [comment]
@lauraweindorf do you mean something like a info pop-up / notification that says:
info: _creating a viewing key for the factory contract will allow you to see your own bids_
notification: "You've created the viewing key to see all your bids"
?

**Comment by baedrik** [comment]
A viewing key is needed if you want to list only the auctions you have participated in (you are either a seller, have an active bid, or won the auction).  The viewing key is also used to view an active bid with an auction, or if you are the seller, to view whether the auction has any active bids (if it does not have any bids, you might decide to extend the auction or change the minimum bid).

The factory address is specified because the factory manages the viewing key so the same one can be used for all auctions

**Comment by lauraweindorf** [comment]
> @lauraweindorf do you mean something like a info pop-up / notification that says:
> info: _creating a viewing key for the factory contract will allow you to see your own bids_
> notification: "You've created the viewing key to see all your bids"
> ?

Yes, Can something like that would be great.

**Comment by lauraweindorf** [comment]
> A viewing key is needed if you want to list only the auctions you have participated in (you are either a seller, have an active bid, or won the auction). The viewing key is also used to view an active bid with an auction, or if you are the seller, to view whether the auction has any active bids (if it does not have any bids, you might decide to extend the auction closing time or change the minimum bid).
> 
> The factory address is specified because the factory manages the viewing key so the same one can be used for all auctions

Thank you, Baedrik! Making more sense to me now 😄

**Comment by cankisagun** [comment]
@the-dusky based on baedrick's comment lets do the following:

1) add a info box when creating a viewing key that says:
" Viewing key for the factory contract will allow you to see the auctions you have participated in as a buyer and seller"

2) notification after the viewing key is created:
" You have successfully created a viewing key. You will now be able to see your active bids or whether there are active bids in an auction you have created"

**Comment by lauraweindorf** [comment]
#1 above is verified, but after creating the viewing key, there is no additional message displayed for #2:

"You have successfully created a viewing key. You will now be able to see your active bids or whether there are active bids in an auction you have created"
