### ISSUE TITLE
Not able to set filter to view auctions created by me

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#22]
I created an auction and also the viewing key (as part of the new auction process). I can see the viewing key, but the filter to select auctions create by me is disabled.

![image](https://user-images.githubusercontent.com/436905/105762326-3f45d500-5f22-11eb-94a7-aac7c9b2e726.png)

Also, in Grid or List view when the user is viewing the auctions, it would be helpful to denote in some visual way which ones are my auctions.

**Comment by cankisagun** [comment]
We probably want to add a tab named "my page" or "dashboard" in order to show that information. Add a note for myself to open a specific issue

**Comment by cankisagun** [comment]
Let's kill that filter now if it's hard to incorporate but get to it first thing after the release next week @the-dusky

**Comment by cankisagun** [comment]
Actually scratch my comment above. It's very hard to currently keep track of things, so I would say this is a must feature. 
If possible can we also show auctions that Alice bid for (not only created) in this tab? @the-dusky

**Comment by lauraweindorf** [comment]
I believe this was addressed as I'm now seeing "My Auctions" in a left-side panel and can choose between Buyer/Seller to see current and past auctions.

Going to close this now. Looks good!
