### ISSUE TITLE
Need validation check when attempting to change the minimum bid to the same value

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#27]
I clicked on "Change minimum bid" and didn't actually change the amount, then clicked "Change ..." and the Secret Auction app started the Keplr interaction.

Just need a check so that the "Change ..." button is disabled until the minimum bid is changed. Or some other solution, like a validator error saying the amount hasn't been changed.

![image](https://user-images.githubusercontent.com/436905/105773055-2c86cc80-5f31-11eb-8f38-3923b4891586.png)

**Comment by cankisagun** [comment]
Laura, thanks for pointing this out! 
This is very low priority. If you are changing the min bid, you should make sure to add a new number.
