### ISSUE TITLE
No UI feedback or change in display when minimum bid is changed on auction

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#28]
I was expecting some sort of message or note that the minimum bid changed, and also in the value shown above in the Auction Info section.

![image](https://user-images.githubusercontent.com/436905/105773528-07468e00-5f32-11eb-9d5d-512429820531.png)

**Comment by cankisagun** [comment]
we are prioritizing adding notifications as mentioned in #40
