### ISSUE TITLE
Getting 404 on Auction Info/Bid page

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#29]
I clicked on an auction using the "Bid" button and once there reloaded the page and got a 404 - not found error.

Going back to the grid or list view the auction is shown, but clicking on the "Bid" button results in the same 404 error

![image](https://user-images.githubusercontent.com/436905/105774560-60fb8800-5f33-11eb-9c9a-1474da11a772.png)

However, it seems to be temporary! A few minutes later going back to the Auctions list and clicking on "Bid" for the auction in question displayed the correct information.

**Comment by the-dusky** [comment]
Fixed
