### ISSUE TITLE
Was able to extend auction even though there was a bid

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#32]
From what I'm understanding in the UI I shouldn't be able to close the auction with options -- to extend it for a time -- if there are any bids, but I was able to here:

![image](https://user-images.githubusercontent.com/436905/105776676-07955800-5f37-11eb-9228-4943ef75c6ec.png)

**Comment by baedrik** [comment]
Looks like this is the same auction in issue #34.  So it looks like it correctly closed the auction and accepted the winning bid instead of extending
