### ISSUE TITLE
Bid page - notification after Bid is placed

### ISSUE THREAD

**Issue by cankisagun** [stakeordie/scrt-auction#4]
When I click on Place Bid, I'm not shown any notification although I can see that tokens have been moved by checking Keplr balances. **Let's add a notification or pop up saying bid submitted or transaction confirmed**. If helpful, pls tag @dogemos on discord to see how to add these

![image](https://user-images.githubusercontent.com/15679491/105410989-c8969800-5c00-11eb-833e-2e6301f05388.png)

Also, the status of having open bids in the auction should change after I submit a bid
![image](https://user-images.githubusercontent.com/15679491/105411802-dbf63300-5c01-11eb-89ed-3c92789ebd7c.png)

**Comment by cankisagun** [comment]
THe prev. screenshots were from a bidders perspective, when I login from my seller account, I also see that there are no open bids for the auction, which in reality is not the case. Is this something we can actually query properly from the contract?
![image](https://user-images.githubusercontent.com/15679491/105413835-a3a42400-5c04-11eb-8fc7-c097e511452c.png)

**Comment by cankisagun** [comment]
This is a good example by Terra Mirror
_Transaction being processed_: we can say transaction pending
![image](https://user-images.githubusercontent.com/15679491/105424517-8035a500-5c15-11eb-8cca-b055fffdf8ac.png)

_TX confirmed_
![image](https://user-images.githubusercontent.com/15679491/105424385-482e6200-5c15-11eb-9201-00410a9b813a.png)

**Comment by cankisagun** [comment]
Similarly when buyer makes a bid, it's hard to understand that the bid was place. Thou we can see that the buyer can retract the bid
![Uploading image.png…]()

**Comment by dogemos** [comment]
Hey @cankisagun, thanks for the head's up.

At this time Keplr doesn't provide a specific endpoint to let the front end know that the 'tx broadcast is complete' / 'tx confirmed'. I believe this would need to be developed on the web interface.

However, we're in the process of refactoring for a more web embeddable Keplr support, and once the refactoring is complete these features can be supported in the future.

**Comment by cankisagun** [comment]
@the-dusky we should also extend this to all actions that users take. You also don't get a notification after you change the min price
