### ISSUE TITLE
Renaming main auction page ACTION currently named BID in different scenarios

### ISSUE THREAD

**Issue by cankisagun** [stakeordie/scrt-auction#47]
Ideally we should think about the main call to action for different uesrs
Bidder
- **Bid** if the action is still open
- **Bid** if the action end time has passed but there are no bids (we can also keep the main action as close). @baedrick can someone bid to an auction which has the end time passed but hasn't been closed?
- **End** if action end time has passed and there are bids

Seller
- **Edit** - if the auction is open (because the seller can change the min price, extend if possible, close, make a bid)
 - **End** in all cases if the auction is closed

**Comment by baedrik** [comment]
@cankisagun Yes, they can still bid if the ends at time has passed but the auction has not been closed.

Going to close #42 as this addresses the same thing

**Comment by baedrik** [comment]
@cankisagun My original thought was to call it View, because it launches the page that reveals all the auction_info.  And there, it offers the buttons/actions available to that address

**Comment by cankisagun** [comment]
we can also call view for this first iteration and keep this issue open if we are not able to meet our deadline of next Monday release - @the-dusky
