### ISSUE TITLE
Change "Enter" button text for auction creator when updating the asking price

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#52]
This is kind of a minor UI improvement suggestion ... after clicking on the "Update Asking Price" button and entering a new price there's a button that says "Enter" to submit the change.

![image](https://user-images.githubusercontent.com/436905/106662146-0637e100-6570-11eb-8dee-1255c2596d6d.png)

I think it should be something other than "Enter" ... like "Submit" or "Update" to affirm the action the user is taking. Unless "Enter" is the preferred action verbiage?

Feel free to close this if it doesn't make sense!

**Comment by the-dusky** [comment]
Changed in dev, live in next release
